name: Gerar Snake

on:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gerar Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ldm-code
          github_token: ${{ secrets.GITHUB_TOKEN }}

          snake_color: "#FFFFFF,#00AEEF,#000000"
         
        

            
          outputs: github-snake.svg

      - name: Commit SVG no branch output
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B output
          git add github-snake.svg
          git commit -m "Atualizar Snake SVG"
          git push -f origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
